version: '3'

services:
  api:
    image: node:12-slim
    command: npm run start:dev
    working_dir: /app
    restart: always
    ports:
      - 3000:3000
    volumes: 
      - .:/app
    environment:
      MONGO_URL: mongodb://root:example@db:27017/myapp?authSource=admin

  db:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: myapp
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  admin:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
